//! Per-model capability rows for Gemini models.
//!
//! Seed values match the current `profile()` output so the parity test passes
//! before the switchover. Authoritative max-output correction (8,192 →
//! 65,536 across Gemini 3.x) lands in a later commit.

use super::{ModelCapabilities, ThinkingSupport};
use crate::catalog::ModelTier;

/// Capability rows for Gemini catalog models.
pub const CAPABILITIES: &[ModelCapabilities] = &[
    ModelCapabilities {
        id: "gemini-3-flash-preview",
        provider: "gemini",
        display_name: "Gemini 3 Flash Preview",
        tier: ModelTier::Recommended,
        model_family: "gemini-3",
        context_window: 1_000_000,
        max_output_tokens: 8_192,
        context_window_beta: None,
        max_output_tokens_beta: None,
        vision: true,
        image_tool_results: true,
        inline_video: true,
        supports_temperature: true,
        supports_top_p: true,
        supports_top_k: true,
        thinking: ThinkingSupport::GeminiThinkingLevel,
        supports_reasoning: false,
        effort_levels: &[],
        supports_web_search: true,
        supports_inference_geo: false,
        supports_compaction: false,
        supports_structured_output: true,
        supports_legacy_penalties: false,
        supports_thinking_budget_legacy: true,
        beta_headers: &[],
        call_timeout_secs: 120,
    },
    ModelCapabilities {
        id: "gemini-3.1-pro-preview",
        provider: "gemini",
        display_name: "Gemini 3.1 Pro Preview",
        tier: ModelTier::Supported,
        model_family: "gemini-3",
        context_window: 1_000_000,
        max_output_tokens: 8_192,
        context_window_beta: None,
        max_output_tokens_beta: None,
        vision: true,
        image_tool_results: true,
        inline_video: true,
        supports_temperature: true,
        supports_top_p: true,
        supports_top_k: true,
        thinking: ThinkingSupport::GeminiThinkingLevel,
        supports_reasoning: false,
        effort_levels: &[],
        supports_web_search: true,
        supports_inference_geo: false,
        supports_compaction: false,
        supports_structured_output: true,
        supports_legacy_penalties: false,
        supports_thinking_budget_legacy: true,
        beta_headers: &[],
        call_timeout_secs: 600,
    },
    ModelCapabilities {
        id: "gemini-3.1-flash-lite-preview",
        provider: "gemini",
        display_name: "Gemini 3.1 Flash Lite Preview",
        tier: ModelTier::Supported,
        model_family: "gemini-3",
        context_window: 1_000_000,
        max_output_tokens: 8_192,
        context_window_beta: None,
        max_output_tokens_beta: None,
        vision: true,
        image_tool_results: true,
        inline_video: true,
        supports_temperature: true,
        supports_top_p: true,
        supports_top_k: true,
        thinking: ThinkingSupport::GeminiThinkingLevel,
        supports_reasoning: false,
        effort_levels: &[],
        supports_web_search: true,
        supports_inference_geo: false,
        supports_compaction: false,
        supports_structured_output: true,
        supports_legacy_penalties: false,
        supports_thinking_budget_legacy: true,
        beta_headers: &[],
        call_timeout_secs: 120,
    },
];
